// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfxrbdmuogcqqsndyhcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmeHJiZG11b2djcXFzbmR5aGNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTk4OTAsImV4cCI6MjA2OTQ3NTg5MH0.Cj3j8ExZO_NUU-WrE385oDDYEvYPhOfJlTilQ_-NPgg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});